import { createContext, useContext, useEffect, useState, ReactNode } from "react";
import { mergeModules } from "@/i18n";


export type Language = "en" | "es" | "pt" | "fr";

export const AVAILABLE_LANGUAGES: { code: Language; label: string; nativeLabel: string }[] = [
  { code: "en", label: "English", nativeLabel: "English" },
  { code: "es", label: "Spanish", nativeLabel: "Español" },
  { code: "pt", label: "Portuguese", nativeLabel: "Português" },
  { code: "fr", label: "French", nativeLabel: "Français" },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Detect the user's preferred language from browser settings.
function detectBrowserLanguage(): Language {
  if (typeof navigator === "undefined") return "en";
  const langs = [navigator.language, ...(navigator.languages || [])];
  for (const raw of langs) {
    const code = raw.toLowerCase().split("-")[0] as Language;
    if (["en", "es", "pt", "fr"].includes(code)) return code;
  }
  return "en";
}

const en = {
  // Navigation
  nav_dashboard: "Dashboard",
  nav_notes: "Notes",
  nav_entities: "Entities",
  nav_insights: "Insights",
  nav_vault: "Vault",
  nav_projects: "Projects",
  nav_activities: "Activities",
  nav_graph: "Graph",
  nav_profile: "Profile",
  nav_subscription: "Subscription",
  nav_support: "Support",
  nav_logout: "Log out",
  nav_settings: "Settings",
  nav_more: "More",

  // Common
  common_save: "Save",
  common_cancel: "Cancel",
  common_delete: "Delete",
  common_edit: "Edit",
  common_create: "Create",
  common_search: "Search",
  common_loading: "Loading…",
  common_back: "Back",
  common_close: "Close",
  common_open: "Open",
  common_confirm: "Confirm",
  common_yes: "Yes",
  common_no: "No",
  common_all: "All",
  common_new: "New",
  common_view_all: "View all",
  common_refresh: "Refresh",
  common_language: "Language",
  common_chooseLanguage: "Choose the interface language.",
  common_of: "of",
  common_unlimited: "Unlimited",
  common_used: "used",
  common_error: "Error",
  common_tryAgain: "Please try again",
  common_upgrade: "Upgrade",
  common_download: "Download",

  // Auth
  auth_signOut: "Sign out?",
  auth_signOutDesc: "You will be signed out of your account. Continue?",

  // Dashboard
  dashboard_overview: "Overview",
  dashboard_greeting: "Welcome back, {name}",
  dashboard_greeting_generic: "Welcome back",
  dashboard_signal: "Signal",
  dashboard_stream: "Stream",
  dashboard_account: "Account",
  dashboard_recentNotes: "Recent notes",
  dashboard_newNote: "New note",
  dashboard_scoreEvolution: "Score evolution",
  dashboard_score: "Score",
  dashboard_14days: "14 days",
  dashboard_1month: "1 month",
  dashboard_3months: "3 months",
  dashboard_1year: "1 year",
  dashboard_total: "Total",
  dashboard_noRecentNotes: "No recent notes",

  // Notes
  notes_title: "Notes",
  notes_new: "New note",
  notes_creating: "Creating…",
  notes_empty: "No notes yet. Create your first one.",
  notes_searchPlaceholder: "Search notes…",
  notes_subtitle: "Your thinking space.",
  notes_index: "Index",
  notes_archive: "Archive",
  notes_recent: "Recent",
  notes_favorites: "Favorites",
  notes_dormant: "Dormant",
  notes_types: "Types",
  notes_allTypes: "All types",
  notes_filters: "Filters",
  notes_untitled: "Untitled",
  notes_dropToVault: "Release to save in Vault",
  notes_uploading: "Uploading…",
  notes_view_archive: "Archive",
  notes_view_favorites: "Favorites",
  notes_view_recent: "Recent",
  notes_view_dormant: "Dormant",
  notes_empty_search: "Nothing matches that search.",
  notes_empty_favorites: "You haven't pinned anything yet.",
  notes_empty_recent: "Nothing written in the last few days.",
  notes_empty_archived: "No dormant entries — your archive is alive.",
  notes_empty_all: "Your archive is still empty.",
  notes_limit: "You've reached the notes limit for your plan.",
  notes_remove_one_title: "Remove this entry?",
  notes_remove_one_desc: "\"{title}\" will be permanently removed from your archive.",
  notes_remove_many_title: "Remove {n} entries?",
  notes_remove_many_title_one: "Remove {n} entry?",
  notes_remove_many_desc: "The selected entries will be permanently removed from your archive.",
  notes_remove: "Remove",
  notes_removing: "Removing…",
  notes_favorite: "Favorite",
  notes_unfavorite: "Unfavorite",
  notes_longPressHint: "Tip: press and hold an entry to select.",

  // Entities
  entities_title: "Entities",
  entities_new: "New entity",
  entities_empty: "No entities yet.",
  entities_empty_search: "Nothing matches that search.",
  entities_empty_all: "No entities yet. Create your first one.",
  entities_subtitle: "People, places and concepts.",
  entities_tagline: "The atoms of your knowledge graph.",
  entities_all: "All entities",
  entities_allAtoms: "All Atoms",
  entities_limit: "You've reached the entities limit for your plan.",
  entities_delete_one_title: "Delete entity?",
  entities_delete_one_desc: "{title} will be permanently removed.",
  entities_delete_many_title: "Delete {n} entities?",
  entities_delete_many_title_one: "Delete {n} entity?",
  entities_delete_many_desc: "The selected entities will be permanently removed.",
  entities_deleting: "Deleting…",
  entities_atom: "atom",
  entities_atoms: "atoms",
  entities_countRemoved: "{n} entities removed",
  entities_countRemoved_one: "{n} entity removed",
  entities_type_PERSON: "Person",
  entities_type_PROJECT: "Project",
  entities_type_TOPIC: "Topic",
  entities_type_ORGANIZATION: "Organization",
  entities_type_ACTIVITY: "Activity",

  // Selection / list shared
  select_done: "Done",
  select_selected: "{n} selected",
  select_all: "Select all",
  select_clearAll: "Clear all",
  notes_bulk_removed: "{n} entries removed",
  notes_bulk_removed_one: "{n} entry removed",
  notes_set_type: "Set type",
  notes_new_type: "New type…",
  notes_new_type_prompt: "New type name",
  notes_bulk_type_applied: "Type applied to {n} notes",
  editor_commands: "Editor commands",
  list_showing_entries: "Showing {n} entries",
  list_showing_entries_one: "Showing {n} entry",
  list_showing_atoms: "Showing {n} atoms",
  list_showing_atoms_one: "Showing {n} atom",
  list_sortBy: "Sort by:",
  list_sort_creation: "Creation",
  list_sort_modification: "Modification",
  list_sort_recent: "Recent",
  list_sort_oldest: "Oldest",
  list_count_entries: "{n} entries",
  list_count_entries_one: "{n} entry",
  rel_today: "today",
  rel_yesterday: "yesterday",
  rel_dAgo: "{n}d ago",
  rel_wAgo: "{n}w ago",

  // Activities
  activities_title: "Activities",
  activities_new: "New activity",
  activities_empty: "No activities yet.",
  activities_subtitle: "Track your daily activities and task history.",

  // Projects
  projects_title: "Projects",
  projects_new: "New project",
  projects_empty: "No projects yet.",
  projects_subtitle: "Track your project activities and milestones.",

  // Insights
  insights_title: "Insights",
  insights_subtitle: "Signals from your second brain.",

  // Graph
  graph_title: "Knowledge Graph",
  graph_empty: "No data to display in the graph.",

  // Vault
  vault_title: "Vault",
  vault_upload: "Upload",
  vault_empty: "Your vault is empty.",
  vault_subtitle: "All files uploaded to your notes.",

  // Profile
  profile_title: "Profile",
  profile_settings: "Settings",
  profile_subtitle: "Manage your account credentials and application preferences.",
  profile_accountDetails: "Account Details",
  profile_prefsAppearance: "Preferences",
  profile_username: "Username",
  profile_usernamePlaceholder: "Your username",
  profile_emailAddress: "Email Address",
  profile_currentPlan: "Current Plan",
  profile_memberSince: "Member Since",
  profile_saveChanges: "Save changes",
  profile_saveConfirmTitle: "Save profile changes?",
  profile_saveConfirmDesc: "Your username will be updated across your account network.",
  profile_secureAuth: "Secure Authentication",
  profile_secureAuthDesc: "Verified and connected via Google Sign-In.",
  profile_importMd: "Import Markdown",
  profile_importMdDesc: "Bring notes from Obsidian, Logseq, or any folder of .md files. Entities are detected automatically — you confirm.",
  profile_importMdBtn: "Import Markdown Files",
  profile_history: "History Retention",
  profile_securityLayer: "Security Layer",
  profile_securityLayerDesc: "Active session tokens are isolated and protected.",
  profile_offlineSync: "Offline & Sync",
  profile_syncNow: "Sync now",
  profile_syncing: "Syncing…",
  profile_upToDate: "Up to date",
  profile_workingOffline: "Working offline",
  profile_lastSync: "Last sync: {time}",
  profile_supportCenter: "Support center",
  profile_supportCenterDesc: "FAQ, contact, feedback and bug reports.",
  profile_sendFeedback: "Send feedback",
  profile_reportBug: "Report a bug",
  profile_planUsage: "Plan Usage & Limits",
  profile_vaultLimit: "Vault Limit",
  profile_uploadMetadata: "Upload Metadata",
  profile_historyDays: "{n} days",
  profile_exportData: "Export Data",
  profile_downloadBackup: "Download Backup",
  profile_exporting: "Exporting…",
  profile_locked: "Locked",
  profile_language: "Language",
  profile_languageDesc: "Change the interface language.",
  profile_backupOk: "Backup downloaded successfully",
  profile_backupFailed: "Export failed",
  profile_updated: "Profile updated",
  profile_updateFailed: "Error saving profile",
  profile_offlineToast: "You're offline. Changes will sync when you're back online.",

  // Plan / Usage
  planLimits: "Plan Limits",
  usageSync: "Usage synchronized with your account.",
  notes: "Notes",
  entities: "Entities",
  activities: "Activities",
  vault: "Vault",
  history: "History",
  days: "days",
  unlimited: "Unlimited",
  usage_used: "used",

  // Legal
  profile_legal: "Legal",
  profile_reviewLegal: "Review our terms and privacy policy.",
  profile_terms: "Terms",
  profile_privacy: "Privacy",
};

type Dict = Partial<typeof en>;

const es: Dict = {
  nav_dashboard: "Panel",
  nav_notes: "Notas",
  nav_entities: "Entidades",
  nav_insights: "Análisis",
  nav_vault: "Bóveda",
  nav_projects: "Proyectos",
  nav_activities: "Actividades",
  nav_graph: "Grafo",
  nav_profile: "Perfil",
  nav_subscription: "Suscripción",
  nav_support: "Soporte",
  nav_logout: "Cerrar sesión",
  nav_settings: "Ajustes",
  nav_more: "Más",

  common_save: "Guardar",
  common_cancel: "Cancelar",
  common_delete: "Eliminar",
  common_edit: "Editar",
  common_create: "Crear",
  common_search: "Buscar",
  common_loading: "Cargando…",
  common_back: "Atrás",
  common_close: "Cerrar",
  common_open: "Abrir",
  common_confirm: "Confirmar",
  common_yes: "Sí",
  common_no: "No",
  common_all: "Todos",
  common_new: "Nuevo",
  common_view_all: "Ver todo",
  common_refresh: "Actualizar",
  common_language: "Idioma",
  common_chooseLanguage: "Elige el idioma de la interfaz.",
  common_of: "de",
  common_unlimited: "Ilimitado",
  common_used: "usado",
  common_error: "Error",
  common_tryAgain: "Inténtalo de nuevo",
  common_upgrade: "Mejorar",
  common_download: "Descargar",

  auth_signOut: "¿Cerrar sesión?",
  auth_signOutDesc: "Se cerrará tu sesión. ¿Continuar?",

  dashboard_overview: "Resumen",
  dashboard_greeting: "Bienvenido de nuevo, {name}",
  dashboard_greeting_generic: "Bienvenido de nuevo",
  dashboard_signal: "Señal",
  dashboard_stream: "Flujo",
  dashboard_account: "Cuenta",
  dashboard_recentNotes: "Notas recientes",
  dashboard_newNote: "Nueva nota",
  dashboard_scoreEvolution: "Evolución de puntuación",
  dashboard_score: "Puntuación",
  dashboard_14days: "14 días",
  dashboard_1month: "1 mes",
  dashboard_3months: "3 meses",
  dashboard_1year: "1 año",
  dashboard_total: "Total",
  dashboard_noRecentNotes: "Sin notas recientes",

  notes_title: "Notas",
  notes_new: "Nueva nota",
  notes_empty: "Aún no hay notas. Crea la primera.",
  notes_searchPlaceholder: "Buscar notas…",
  notes_subtitle: "Tu espacio de pensamiento.",

  entities_title: "Entidades",
  entities_new: "Nueva entidad",
  entities_empty: "Aún no hay entidades.",
  entities_subtitle: "Personas, lugares y conceptos.",

  activities_title: "Actividades",
  activities_new: "Nueva actividad",
  activities_empty: "Aún no hay actividades.",
  activities_subtitle: "Sigue tus actividades diarias y el historial de tareas.",

  projects_title: "Proyectos",
  projects_new: "Nuevo proyecto",
  projects_empty: "Aún no hay proyectos.",
  projects_subtitle: "Sigue tus actividades y hitos de proyecto.",

  insights_title: "Análisis",
  insights_subtitle: "Señales de tu segundo cerebro.",

  graph_title: "Grafo de conocimiento",
  graph_empty: "Sin datos para mostrar en el grafo.",

  vault_title: "Bóveda",
  vault_upload: "Subir",
  vault_empty: "Tu bóveda está vacía.",
  vault_subtitle: "Todos los archivos subidos a tus notas.",

  profile_title: "Perfil",
  profile_settings: "Ajustes",
  profile_subtitle: "Gestiona las credenciales de tu cuenta y las preferencias de la aplicación.",
  profile_accountDetails: "Datos de la cuenta",
  profile_prefsAppearance: "Preferencias",
  profile_username: "Nombre de usuario",
  profile_usernamePlaceholder: "Tu nombre de usuario",
  profile_emailAddress: "Correo electrónico",
  profile_currentPlan: "Plan actual",
  profile_memberSince: "Miembro desde",
  profile_saveChanges: "Guardar cambios",
  profile_saveConfirmTitle: "¿Guardar cambios del perfil?",
  profile_saveConfirmDesc: "Tu nombre de usuario se actualizará en toda tu cuenta.",
  profile_secureAuth: "Autenticación segura",
  profile_secureAuthDesc: "Verificado y conectado con Google Sign-In.",
  profile_importMd: "Importar Markdown",
  profile_importMdDesc: "Trae notas desde Obsidian, Logseq o cualquier carpeta de .md. Las entidades se detectan automáticamente — tú confirmas.",
  profile_importMdBtn: "Importar archivos Markdown",
  profile_history: "Retención del historial",
  profile_securityLayer: "Capa de seguridad",
  profile_securityLayerDesc: "Los tokens de sesión activos están aislados y protegidos.",
  profile_offlineSync: "Sin conexión y sincronización",
  profile_syncNow: "Sincronizar ahora",
  profile_syncing: "Sincronizando…",
  profile_upToDate: "Todo al día",
  profile_workingOffline: "Trabajando sin conexión",
  profile_lastSync: "Última sincronización: {time}",
  profile_supportCenter: "Centro de soporte",
  profile_supportCenterDesc: "FAQ, contacto, comentarios y reportes de errores.",
  profile_sendFeedback: "Enviar comentarios",
  profile_reportBug: "Reportar un error",
  profile_planUsage: "Uso y límites del plan",
  profile_vaultLimit: "Límite de bóveda",
  profile_uploadMetadata: "Metadatos de subida",
  profile_historyDays: "{n} días",
  profile_exportData: "Exportar datos",
  profile_downloadBackup: "Descargar respaldo",
  profile_exporting: "Exportando…",
  profile_locked: "Bloqueado",
  profile_language: "Idioma",
  profile_languageDesc: "Cambia el idioma de la interfaz.",
  profile_backupOk: "Respaldo descargado con éxito",
  profile_backupFailed: "Error al exportar",
  profile_updated: "Perfil actualizado",
  profile_updateFailed: "Error al guardar el perfil",
  profile_offlineToast: "Estás sin conexión. Los cambios se sincronizarán al reconectar.",

  planLimits: "Límites del plan",
  usageSync: "Uso sincronizado con tu cuenta.",
  notes: "Notas",
  entities: "Entidades",
  activities: "Actividades",
  vault: "Bóveda",
  history: "Historial",
  days: "días",
  unlimited: "Ilimitado",
  usage_used: "utilizadas",

  profile_legal: "Legal",
  profile_reviewLegal: "Revisa nuestros términos y la política de privacidad.",
  profile_terms: "Términos",
  profile_privacy: "Privacidad",
};

const pt: Dict = {
  nav_dashboard: "Painel",
  nav_notes: "Notas",
  nav_entities: "Entidades",
  nav_insights: "Insights",
  nav_vault: "Vault",
  nav_projects: "Projetos",
  nav_activities: "Atividades",
  nav_graph: "Grafo",
  nav_profile: "Perfil",
  nav_subscription: "Assinatura",
  nav_support: "Suporte",
  nav_logout: "Sair",
  nav_settings: "Ajustes",
  nav_more: "Mais",

  common_save: "Salvar",
  common_cancel: "Cancelar",
  common_delete: "Excluir",
  common_edit: "Editar",
  common_create: "Criar",
  common_search: "Buscar",
  common_loading: "Carregando…",
  common_back: "Voltar",
  common_close: "Fechar",
  common_open: "Abrir",
  common_confirm: "Confirmar",
  common_yes: "Sim",
  common_no: "Não",
  common_all: "Todos",
  common_new: "Novo",
  common_view_all: "Ver tudo",
  common_refresh: "Atualizar",
  common_language: "Idioma",
  common_chooseLanguage: "Escolha o idioma da interface.",
  common_of: "de",
  common_unlimited: "Ilimitado",
  common_used: "usado",
  common_error: "Erro",
  common_tryAgain: "Tente novamente",
  common_upgrade: "Fazer upgrade",
  common_download: "Baixar",

  auth_signOut: "Sair?",
  auth_signOutDesc: "Você sairá da sua conta. Continuar?",

  dashboard_overview: "Visão geral",
  dashboard_greeting: "Bem-vindo de volta, {name}",
  dashboard_greeting_generic: "Bem-vindo de volta",
  dashboard_signal: "Sinal",
  dashboard_stream: "Fluxo",
  dashboard_account: "Conta",
  dashboard_recentNotes: "Notas recentes",
  dashboard_newNote: "Nova nota",
  dashboard_scoreEvolution: "Evolução da pontuação",
  dashboard_score: "Pontuação",
  dashboard_14days: "14 dias",
  dashboard_1month: "1 mês",
  dashboard_3months: "3 meses",
  dashboard_1year: "1 ano",
  dashboard_total: "Total",
  dashboard_noRecentNotes: "Sem notas recentes",

  notes_title: "Notas",
  notes_new: "Nova nota",
  notes_creating: "Criando…",
  notes_empty: "Sem notas ainda. Crie a primeira.",
  notes_searchPlaceholder: "Buscar notas…",
  notes_subtitle: "Seu espaço de pensamento.",
  notes_index: "Índice",
  notes_archive: "Arquivo",
  notes_recent: "Recentes",
  notes_favorites: "Favoritas",
  notes_dormant: "Dormentes",
  notes_types: "Tipos",
  notes_allTypes: "Todos os tipos",
  notes_filters: "Filtros",
  notes_untitled: "Sem título",
  notes_dropToVault: "Solte para salvar no Vault",
  notes_uploading: "Enviando…",
  notes_view_archive: "Arquivo",
  notes_view_favorites: "Favoritas",
  notes_view_recent: "Recentes",
  notes_view_dormant: "Dormentes",
  notes_empty_search: "Nada corresponde a essa busca.",
  notes_empty_favorites: "Você ainda não fixou nada.",
  notes_empty_recent: "Nada escrito nos últimos dias.",
  notes_empty_archived: "Sem entradas dormentes — seu arquivo está vivo.",
  notes_empty_all: "Seu arquivo ainda está vazio.",
  notes_limit: "Você atingiu o limite de notas do seu plano.",
  notes_remove_one_title: "Remover esta entrada?",
  notes_remove_one_desc: "\"{title}\" será removida permanentemente do seu arquivo.",
  notes_remove_many_title: "Remover {n} entradas?",
  notes_remove_many_title_one: "Remover {n} entrada?",
  notes_remove_many_desc: "As entradas selecionadas serão removidas permanentemente do seu arquivo.",
  notes_remove: "Remover",
  notes_removing: "Removendo…",
  notes_favorite: "Favoritar",
  notes_unfavorite: "Desfavoritar",
  notes_longPressHint: "Dica: pressione e segure uma entrada para selecionar.",

  entities_title: "Entidades",
  entities_new: "Nova entidade",
  entities_empty: "Sem entidades ainda.",
  entities_empty_search: "Nada corresponde a essa busca.",
  entities_empty_all: "Sem entidades. Crie a primeira.",
  entities_subtitle: "Pessoas, lugares e conceitos.",
  entities_tagline: "Os átomos do seu grafo de conhecimento.",
  entities_all: "Todas as entidades",
  entities_allAtoms: "Todos os átomos",
  entities_limit: "Você atingiu o limite de entidades do seu plano.",
  entities_delete_one_title: "Excluir entidade?",
  entities_delete_one_desc: "{title} será removida permanentemente.",
  entities_delete_many_title: "Excluir {n} entidades?",
  entities_delete_many_title_one: "Excluir {n} entidade?",
  entities_delete_many_desc: "As entidades selecionadas serão removidas permanentemente.",
  entities_deleting: "Excluindo…",
  entities_atom: "átomo",
  entities_atoms: "átomos",
  entities_countRemoved: "{n} entidades removidas",
  entities_countRemoved_one: "{n} entidade removida",
  entities_type_PERSON: "Pessoa",
  entities_type_PROJECT: "Projeto",
  entities_type_TOPIC: "Tópico",
  entities_type_ORGANIZATION: "Organização",
  entities_type_ACTIVITY: "Atividade",

  select_done: "Concluir",
  select_selected: "{n} selecionadas",
  select_all: "Selecionar tudo",
  select_clearAll: "Limpar seleção",
  notes_bulk_removed: "{n} entradas removidas",
  notes_bulk_removed_one: "{n} entrada removida",
  notes_set_type: "Definir tipo",
  notes_new_type: "Novo tipo…",
  notes_new_type_prompt: "Nome do novo tipo",
  notes_bulk_type_applied: "Tipo aplicado a {n} notas",
  editor_commands: "Comandos do editor",
  list_showing_entries: "Mostrando {n} entradas",
  list_showing_entries_one: "Mostrando {n} entrada",
  list_showing_atoms: "Mostrando {n} átomos",
  list_showing_atoms_one: "Mostrando {n} átomo",
  list_sortBy: "Ordenar por:",
  list_sort_creation: "Criação",
  list_sort_modification: "Modificação",
  list_sort_recent: "Recentes",
  list_sort_oldest: "Antigos",
  list_count_entries: "{n} entradas",
  list_count_entries_one: "{n} entrada",
  rel_today: "hoje",
  rel_yesterday: "ontem",
  rel_dAgo: "há {n}d",
  rel_wAgo: "há {n}sem",


  activities_title: "Atividades",
  activities_new: "Nova atividade",
  activities_empty: "Sem atividades ainda.",
  activities_subtitle: "Acompanhe suas atividades diárias e o histórico de tarefas.",

  projects_title: "Projetos",
  projects_new: "Novo projeto",
  projects_empty: "Sem projetos ainda.",
  projects_subtitle: "Acompanhe as atividades e marcos dos seus projetos.",

  insights_title: "Insights",
  insights_subtitle: "Sinais do seu segundo cérebro.",

  graph_title: "Grafo de conhecimento",
  graph_empty: "Sem dados para exibir no grafo.",

  vault_title: "Vault",
  vault_upload: "Enviar",
  vault_empty: "Seu vault está vazio.",
  vault_subtitle: "Todos os arquivos enviados nas suas notas.",

  profile_title: "Perfil",
  profile_settings: "Ajustes",
  profile_subtitle: "Gerencie as credenciais da sua conta e as preferências do aplicativo.",
  profile_accountDetails: "Dados da conta",
  profile_prefsAppearance: "Preferências",
  profile_username: "Nome de usuário",
  profile_usernamePlaceholder: "Seu nome de usuário",
  profile_emailAddress: "Email",
  profile_currentPlan: "Plano atual",
  profile_memberSince: "Membro desde",
  profile_saveChanges: "Salvar alterações",
  profile_saveConfirmTitle: "Salvar alterações do perfil?",
  profile_saveConfirmDesc: "Seu nome de usuário será atualizado em toda a sua conta.",
  profile_secureAuth: "Autenticação segura",
  profile_secureAuthDesc: "Verificado e conectado via Google Sign-In.",
  profile_importMd: "Importar Markdown",
  profile_importMdDesc: "Traga notas do Obsidian, Logseq ou qualquer pasta de arquivos .md. As entidades são detectadas automaticamente — você confirma.",
  profile_importMdBtn: "Importar arquivos Markdown",
  profile_history: "Retenção do histórico",
  profile_securityLayer: "Camada de segurança",
  profile_securityLayerDesc: "Tokens de sessão ativos são isolados e protegidos.",
  profile_offlineSync: "Offline e sincronização",
  profile_syncNow: "Sincronizar agora",
  profile_syncing: "Sincronizando…",
  profile_upToDate: "Tudo em dia",
  profile_workingOffline: "Trabalhando offline",
  profile_lastSync: "Última sincronização: {time}",
  profile_supportCenter: "Central de suporte",
  profile_supportCenterDesc: "FAQ, contato, feedback e reportes de bugs.",
  profile_sendFeedback: "Enviar feedback",
  profile_reportBug: "Reportar um bug",
  profile_planUsage: "Uso e limites do plano",
  profile_vaultLimit: "Limite do vault",
  profile_uploadMetadata: "Metadados de upload",
  profile_historyDays: "{n} dias",
  profile_exportData: "Exportar dados",
  profile_downloadBackup: "Baixar backup",
  profile_exporting: "Exportando…",
  profile_locked: "Bloqueado",
  profile_language: "Idioma",
  profile_languageDesc: "Altere o idioma da interface.",
  profile_backupOk: "Backup baixado com sucesso",
  profile_backupFailed: "Falha ao exportar",
  profile_updated: "Perfil atualizado",
  profile_updateFailed: "Erro ao salvar o perfil",
  profile_offlineToast: "Você está offline. As alterações serão sincronizadas ao reconectar.",

  planLimits: "Limites do plano",
  usageSync: "Uso sincronizado com sua conta.",
  notes: "Notas",
  entities: "Entidades",
  activities: "Atividades",
  vault: "Vault",
  history: "Histórico",
  days: "dias",
  unlimited: "Ilimitado",
  usage_used: "utilizadas",

  profile_legal: "Legal",
  profile_reviewLegal: "Revise nossos termos e a política de privacidade.",
  profile_terms: "Termos",
  profile_privacy: "Privacidade",
};

const fr: Dict = {
  nav_dashboard: "Tableau de bord",
  nav_notes: "Notes",
  nav_entities: "Entités",
  nav_insights: "Analyses",
  nav_vault: "Coffre-fort",
  nav_projects: "Projets",
  nav_activities: "Activités",
  nav_graph: "Graphe",
  nav_profile: "Profil",
  nav_subscription: "Abonnement",
  nav_support: "Assistance",
  nav_logout: "Déconnexion",
  nav_settings: "Paramètres",
  nav_more: "Plus",

  common_save: "Enregistrer",
  common_cancel: "Annuler",
  common_delete: "Supprimer",
  common_edit: "Modifier",
  common_create: "Créer",
  common_search: "Rechercher",
  common_loading: "Chargement…",
  common_back: "Retour",
  common_close: "Fermer",
  common_open: "Ouvrir",
  common_confirm: "Confirmer",
  common_yes: "Oui",
  common_no: "Non",
  common_all: "Tous",
  common_new: "Nouveau",
  common_view_all: "Tout voir",
  common_refresh: "Actualiser",
  common_language: "Langue",
  common_chooseLanguage: "Choisissez la langue de l'interface.",
  common_of: "sur",
  common_unlimited: "Illimité",
  common_used: "utilisé",
  common_error: "Erreur",
  common_tryAgain: "Veuillez réessayer",
  common_upgrade: "Mettre à niveau",
  common_download: "Télécharger",

  auth_signOut: "Se déconnecter ?",
  auth_signOutDesc: "Vous allez être déconnecté. Continuer ?",

  dashboard_overview: "Vue d'ensemble",
  dashboard_greeting: "Bon retour, {name}",
  dashboard_greeting_generic: "Bon retour",
  dashboard_signal: "Signal",
  dashboard_stream: "Flux",
  dashboard_account: "Compte",
  dashboard_recentNotes: "Notes récentes",
  dashboard_newNote: "Nouvelle note",
  dashboard_scoreEvolution: "Évolution du score",
  dashboard_score: "Score",
  dashboard_14days: "14 jours",
  dashboard_1month: "1 mois",
  dashboard_3months: "3 mois",
  dashboard_1year: "1 an",
  dashboard_total: "Total",
  dashboard_noRecentNotes: "Aucune note récente",

  notes_title: "Notes",
  notes_new: "Nouvelle note",
  notes_empty: "Aucune note pour l'instant. Créez la première.",
  notes_searchPlaceholder: "Rechercher des notes…",
  notes_subtitle: "Votre espace de réflexion.",

  entities_title: "Entités",
  entities_new: "Nouvelle entité",
  entities_empty: "Aucune entité pour l'instant.",
  entities_subtitle: "Personnes, lieux et concepts.",

  activities_title: "Activités",
  activities_new: "Nouvelle activité",
  activities_empty: "Aucune activité pour l'instant.",
  activities_subtitle: "Suivez vos activités quotidiennes et votre historique de tâches.",

  projects_title: "Projets",
  projects_new: "Nouveau projet",
  projects_empty: "Aucun projet pour l'instant.",
  projects_subtitle: "Suivez les activités et les jalons de vos projets.",

  insights_title: "Analyses",
  insights_subtitle: "Signaux de votre second cerveau.",

  graph_title: "Graphe de connaissances",
  graph_empty: "Aucune donnée à afficher dans le graphe.",

  vault_title: "Coffre-fort",
  vault_upload: "Téléverser",
  vault_empty: "Votre coffre est vide.",
  vault_subtitle: "Tous les fichiers téléversés dans vos notes.",

  profile_title: "Profil",
  profile_settings: "Paramètres",
  profile_subtitle: "Gérez les identifiants de votre compte et les préférences de l'application.",
  profile_accountDetails: "Détails du compte",
  profile_prefsAppearance: "Préférences",
  profile_username: "Nom d'utilisateur",
  profile_usernamePlaceholder: "Votre nom d'utilisateur",
  profile_emailAddress: "Adresse e-mail",
  profile_currentPlan: "Plan actuel",
  profile_memberSince: "Membre depuis",
  profile_saveChanges: "Enregistrer les modifications",
  profile_saveConfirmTitle: "Enregistrer les modifications du profil ?",
  profile_saveConfirmDesc: "Votre nom d'utilisateur sera mis à jour dans tout votre compte.",
  profile_secureAuth: "Authentification sécurisée",
  profile_secureAuthDesc: "Vérifié et connecté via Google Sign-In.",
  profile_importMd: "Importer Markdown",
  profile_importMdDesc: "Importez des notes depuis Obsidian, Logseq, ou tout dossier de fichiers .md. Les entités sont détectées automatiquement — vous confirmez.",
  profile_importMdBtn: "Importer des fichiers Markdown",
  profile_history: "Conservation de l'historique",
  profile_securityLayer: "Couche de sécurité",
  profile_securityLayerDesc: "Les jetons de session actifs sont isolés et protégés.",
  profile_offlineSync: "Hors ligne et synchronisation",
  profile_syncNow: "Synchroniser",
  profile_syncing: "Synchronisation…",
  profile_upToDate: "À jour",
  profile_workingOffline: "Hors ligne",
  profile_lastSync: "Dernière synchro : {time}",
  profile_supportCenter: "Centre d'assistance",
  profile_supportCenterDesc: "FAQ, contact, retours et rapports de bugs.",
  profile_sendFeedback: "Envoyer un retour",
  profile_reportBug: "Signaler un bug",
  profile_planUsage: "Utilisation et limites du plan",
  profile_vaultLimit: "Limite du coffre",
  profile_uploadMetadata: "Métadonnées d'envoi",
  profile_historyDays: "{n} jours",
  profile_exportData: "Exporter les données",
  profile_downloadBackup: "Télécharger la sauvegarde",
  profile_exporting: "Exportation…",
  profile_locked: "Verrouillé",
  profile_language: "Langue",
  profile_languageDesc: "Changer la langue de l'interface.",
  profile_backupOk: "Sauvegarde téléchargée avec succès",
  profile_backupFailed: "Échec de l'export",
  profile_updated: "Profil mis à jour",
  profile_updateFailed: "Erreur lors de l'enregistrement",
  profile_offlineToast: "Vous êtes hors ligne. Les changements seront synchronisés au retour.",

  planLimits: "Limites du plan",
  usageSync: "Utilisation synchronisée avec votre compte.",
  notes: "Notes",
  entities: "Entités",
  activities: "Activités",
  vault: "Coffre-fort",
  history: "Historique",
  days: "jours",
  unlimited: "Illimité",
  usage_used: "utilisées",

  profile_legal: "Juridique",
  profile_reviewLegal: "Consultez nos conditions et notre politique de confidentialité.",
  profile_terms: "Conditions",
  profile_privacy: "Confidentialité",
};

const translations: Record<Language, Dict> = { en, es, pt, fr };

// Merge modular dictionaries (src/i18n/*) on top of the base ones.
const mergedTranslations: Record<Language, Record<string, string>> = {
  en: { ...(en as Record<string, string>), ...mergeModules("en") },
  es: { ...(es as Record<string, string>), ...mergeModules("es") },
  pt: { ...(pt as Record<string, string>), ...mergeModules("pt") },
  fr: { ...(fr as Record<string, string>), ...mergeModules("fr") },
};


const missingWarned = new Set<string>();

function interpolate(str: string, vars?: Record<string, string | number>): string {
  if (!vars) return str;
  return str.replace(/\{(\w+)\}/g, (_, k) => (vars[k] !== undefined ? String(vars[k]) : `{${k}}`));
}

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const saved = localStorage.getItem("language") as Language | null;
    if (saved && ["en", "es", "pt", "fr"].includes(saved)) return saved;
    return detectBrowserLanguage();
  });

  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = language;
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem("language", lang);
    } catch {}
  };

  const t = (key: string, vars?: Record<string, string | number>): string => {
    const dict = mergedTranslations[language];
    const fallback = mergedTranslations.en;

    const value = dict[key] ?? fallback[key];
    if (value === undefined) {
      if (import.meta.env.DEV && !missingWarned.has(key)) {
        missingWarned.add(key);
        // eslint-disable-next-line no-console
        console.warn(`[i18n] Missing translation key: "${key}"`);
      }
      return key;
    }
    return interpolate(value, vars);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
