import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "es" | "pt" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    nav_dashboard: "Dashboard",
    nav_notes: "Notes",
    nav_entities: "Entities",
    nav_insights: "Insights",
    nav_vault: "Vault",
    nav_projects: "Projects",
    nav_activities: "Activities",
    nav_graph: "Graph",
    nav_profile: "Profile",
    nav_subscription: "Subscription",
    nav_logout: "Logout",
    nav_settings: "Settings",
    // Common
    common_save: "Save",
    common_cancel: "Cancel",
    common_delete: "Delete",
    common_edit: "Edit",
    common_create: "Create",
    common_search: "Search",
    common_loading: "Loading…",
    common_back: "Back",
    common_close: "Close",
    common_open: "Open",
    common_confirm: "Confirm",
    common_yes: "Yes",
    common_no: "No",
    common_all: "All",
    common_new: "New",
    common_view_all: "View all",
    common_refresh: "Refresh",
    common_language: "Language",
    common_chooseLanguage: "Choose your interface language.",
    // Auth
    auth_signOut: "Sign out?",
    auth_signOutDesc: "You will be signed out of your account. Continue?",
    // Dashboard
    dashboard_overview: "Overview",
    dashboard_greeting: "Welcome back",
    dashboard_signal: "Signal",
    dashboard_stream: "Stream",
    dashboard_account: "Account",
    dashboard_recentNotes: "Recent notes",
    dashboard_score: "Score",
    dashboard_14days: "14 Days",
    dashboard_1month: "1 Month",
    dashboard_3months: "3 Months",
    dashboard_1year: "1 Year",
    dashboard_total: "Total",
    // Notes
    notes_title: "Notes",
    notes_new: "New note",
    notes_empty: "No notes yet. Create your first one.",
    notes_searchPlaceholder: "Search notes…",
    // Entities
    entities_title: "Entities",
    entities_new: "New entity",
    entities_empty: "No entities yet.",
    // Activities
    activities_title: "Activities",
    activities_new: "New activity",
    activities_empty: "No activities yet.",
    // Projects
    projects_title: "Projects",
    projects_new: "New project",
    projects_empty: "No projects yet.",
    // Insights
    insights_title: "Insights",
    // Graph
    graph_title: "Knowledge Graph",
    graph_empty: "No data to display in the graph.",
    // Vault
    vault_title: "Vault",
    vault_upload: "Upload",
    vault_empty: "Your vault is empty.",
    // Profile
    profile: "Profile",
    accountData: "Account Data",
    updateInfo: "Update your main information.",
    username: "Username",
    email: "Email",
    currentPlan: "Current Plan",
    memberSince: "Member since",
    saveChanges: "Save changes",
    preferences: "Preferences",
    chooseTheme: "Choose the interface theme.",
    darkMode: "Dark mode",
    toggleDark: "Toggle between light and dark visual.",
    accountStatus: "Account Status",
    emailVerified: "Email verified",
    emailPending: "Email pending verification",
    planLimits: "Plan Limits",
    usageSync: "Usage synchronized with your account.",
    history: "History",
    days: "days",
    notes: "Notes",
    entities: "Entities",
    activities: "Activities",
    vault: "Vault",
    unlimited: "Unlimited",
  },
  es: {
    nav_dashboard: "Panel",
    nav_notes: "Notas",
    nav_entities: "Entidades",
    nav_insights: "Análisis",
    nav_vault: "Bóveda",
    nav_projects: "Proyectos",
    nav_activities: "Actividades",
    nav_graph: "Grafo",
    nav_profile: "Perfil",
    nav_subscription: "Suscripción",
    nav_logout: "Cerrar sesión",
    nav_settings: "Ajustes",
    common_save: "Guardar",
    common_cancel: "Cancelar",
    common_delete: "Eliminar",
    common_edit: "Editar",
    common_create: "Crear",
    common_search: "Buscar",
    common_loading: "Cargando…",
    common_back: "Atrás",
    common_close: "Cerrar",
    common_open: "Abrir",
    common_confirm: "Confirmar",
    common_yes: "Sí",
    common_no: "No",
    common_all: "Todos",
    common_new: "Nuevo",
    common_view_all: "Ver todo",
    common_refresh: "Actualizar",
    common_language: "Idioma",
    common_chooseLanguage: "Elige el idioma de la interfaz.",
    auth_signOut: "¿Cerrar sesión?",
    auth_signOutDesc: "Se cerrará tu sesión. ¿Continuar?",
    dashboard_overview: "Resumen",
    dashboard_greeting: "Bienvenido de nuevo",
    dashboard_signal: "Señal",
    dashboard_stream: "Flujo",
    dashboard_account: "Cuenta",
    dashboard_recentNotes: "Notas recientes",
    dashboard_score: "Puntuación",
    dashboard_14days: "14 días",
    dashboard_1month: "1 mes",
    dashboard_3months: "3 meses",
    dashboard_1year: "1 año",
    dashboard_total: "Total",
    notes_title: "Notas",
    notes_new: "Nueva nota",
    notes_empty: "Aún no hay notas. Crea la primera.",
    notes_searchPlaceholder: "Buscar notas…",
    entities_title: "Entidades",
    entities_new: "Nueva entidad",
    entities_empty: "Aún no hay entidades.",
    activities_title: "Actividades",
    activities_new: "Nueva actividad",
    activities_empty: "Aún no hay actividades.",
    projects_title: "Proyectos",
    projects_new: "Nuevo proyecto",
    projects_empty: "Aún no hay proyectos.",
    insights_title: "Análisis",
    graph_title: "Grafo de conocimiento",
    graph_empty: "Sin datos para mostrar en el grafo.",
    vault_title: "Bóveda",
    vault_upload: "Subir",
    vault_empty: "Tu bóveda está vacía.",
    profile: "Perfil",
    accountData: "Datos de la Cuenta",
    updateInfo: "Actualiza tu información principal.",
    username: "Nombre de usuario",
    email: "Correo electrónico",
    currentPlan: "Plan Actual",
    memberSince: "Miembro desde",
    saveChanges: "Guardar cambios",
    preferences: "Preferencias",
    chooseTheme: "Elige el tema de la interfaz.",
    darkMode: "Modo oscuro",
    toggleDark: "Alternar entre visual claro y oscuro.",
    accountStatus: "Estado de la Cuenta",
    emailVerified: "Correo verificado",
    emailPending: "Correo pendiente de verificación",
    planLimits: "Límites del Plan",
    usageSync: "Uso sincronizado con tu cuenta.",
    history: "Historial",
    days: "días",
    notes: "Notas",
    entities: "Entidades",
    activities: "Actividades",
    vault: "Bóveda",
    unlimited: "Ilimitado",
  },
  pt: {
    nav_dashboard: "Painel",
    nav_notes: "Notas",
    nav_entities: "Entidades",
    nav_insights: "Insights",
    nav_vault: "Vault",
    nav_projects: "Projetos",
    nav_activities: "Atividades",
    nav_graph: "Grafo",
    nav_profile: "Perfil",
    nav_subscription: "Assinatura",
    nav_logout: "Sair",
    nav_settings: "Ajustes",
    common_save: "Salvar",
    common_cancel: "Cancelar",
    common_delete: "Excluir",
    common_edit: "Editar",
    common_create: "Criar",
    common_search: "Buscar",
    common_loading: "Carregando…",
    common_back: "Voltar",
    common_close: "Fechar",
    common_open: "Abrir",
    common_confirm: "Confirmar",
    common_yes: "Sim",
    common_no: "Não",
    common_all: "Todos",
    common_new: "Novo",
    common_view_all: "Ver tudo",
    common_refresh: "Atualizar",
    common_language: "Idioma",
    common_chooseLanguage: "Escolha o idioma da interface.",
    auth_signOut: "Sair?",
    auth_signOutDesc: "Você sairá da sua conta. Continuar?",
    dashboard_overview: "Visão geral",
    dashboard_greeting: "Bem-vindo de volta",
    dashboard_signal: "Sinal",
    dashboard_stream: "Fluxo",
    dashboard_account: "Conta",
    dashboard_recentNotes: "Notas recentes",
    dashboard_score: "Pontuação",
    dashboard_14days: "14 dias",
    dashboard_1month: "1 mês",
    dashboard_3months: "3 meses",
    dashboard_1year: "1 ano",
    dashboard_total: "Total",
    notes_title: "Notas",
    notes_new: "Nova nota",
    notes_empty: "Sem notas ainda. Crie a primeira.",
    notes_searchPlaceholder: "Buscar notas…",
    entities_title: "Entidades",
    entities_new: "Nova entidade",
    entities_empty: "Sem entidades ainda.",
    activities_title: "Atividades",
    activities_new: "Nova atividade",
    activities_empty: "Sem atividades ainda.",
    projects_title: "Projetos",
    projects_new: "Novo projeto",
    projects_empty: "Sem projetos ainda.",
    insights_title: "Insights",
    graph_title: "Grafo de conhecimento",
    graph_empty: "Sem dados para exibir no grafo.",
    vault_title: "Vault",
    vault_upload: "Enviar",
    vault_empty: "Seu vault está vazio.",
    profile: "Perfil",
    accountData: "Dados da Conta",
    updateInfo: "Atualize suas informações principais.",
    username: "Nome de usuário",
    email: "Email",
    currentPlan: "Plano Atual",
    memberSince: "Membro desde",
    saveChanges: "Salvar alterações",
    preferences: "Preferências",
    chooseTheme: "Escolha o tema da interface.",
    darkMode: "Modo escuro",
    toggleDark: "Alterne entre o visual claro e escuro.",
    accountStatus: "Status da Conta",
    emailVerified: "Email verificado",
    emailPending: "Email pendente de verificação",
    planLimits: "Limites do Plano",
    usageSync: "Uso sincronizado com sua conta.",
    history: "Histórico",
    days: "dias",
    notes: "Notas",
    entities: "Entidades",
    activities: "Atividades",
    vault: "Vault",
    unlimited: "Ilimitado",
  },
  fr: {
    nav_dashboard: "Tableau de bord",
    nav_notes: "Notes",
    nav_entities: "Entités",
    nav_insights: "Analyses",
    nav_vault: "Coffre-fort",
    nav_projects: "Projets",
    nav_activities: "Activités",
    nav_graph: "Graphe",
    nav_profile: "Profil",
    nav_subscription: "Abonnement",
    nav_logout: "Déconnexion",
    nav_settings: "Paramètres",
    common_save: "Enregistrer",
    common_cancel: "Annuler",
    common_delete: "Supprimer",
    common_edit: "Modifier",
    common_create: "Créer",
    common_search: "Rechercher",
    common_loading: "Chargement…",
    common_back: "Retour",
    common_close: "Fermer",
    common_open: "Ouvrir",
    common_confirm: "Confirmer",
    common_yes: "Oui",
    common_no: "Non",
    common_all: "Tous",
    common_new: "Nouveau",
    common_view_all: "Tout voir",
    common_refresh: "Actualiser",
    common_language: "Langue",
    common_chooseLanguage: "Choisissez la langue de l'interface.",
    auth_signOut: "Se déconnecter ?",
    auth_signOutDesc: "Vous allez être déconnecté. Continuer ?",
    dashboard_overview: "Vue d'ensemble",
    dashboard_greeting: "Bon retour",
    dashboard_signal: "Signal",
    dashboard_stream: "Flux",
    dashboard_account: "Compte",
    dashboard_recentNotes: "Notes récentes",
    dashboard_score: "Score",
    dashboard_14days: "14 jours",
    dashboard_1month: "1 mois",
    dashboard_3months: "3 mois",
    dashboard_1year: "1 an",
    dashboard_total: "Total",
    notes_title: "Notes",
    notes_new: "Nouvelle note",
    notes_empty: "Aucune note pour l'instant. Créez la première.",
    notes_searchPlaceholder: "Rechercher des notes…",
    entities_title: "Entités",
    entities_new: "Nouvelle entité",
    entities_empty: "Aucune entité pour l'instant.",
    activities_title: "Activités",
    activities_new: "Nouvelle activité",
    activities_empty: "Aucune activité pour l'instant.",
    projects_title: "Projets",
    projects_new: "Nouveau projet",
    projects_empty: "Aucun projet pour l'instant.",
    insights_title: "Analyses",
    graph_title: "Graphe de connaissances",
    graph_empty: "Aucune donnée à afficher dans le graphe.",
    vault_title: "Coffre-fort",
    vault_upload: "Téléverser",
    vault_empty: "Votre coffre est vide.",
    profile: "Profil",
    accountData: "Données du Compte",
    updateInfo: "Mettez à jour vos informations principales.",
    username: "Nom d'utilisateur",
    email: "Email",
    currentPlan: "Plan Actuel",
    memberSince: "Membre depuis",
    saveChanges: "Sauvegarder les modifications",
    preferences: "Préférences",
    chooseTheme: "Choisissez le thème de l'interface.",
    darkMode: "Mode sombre",
    toggleDark: "Basculer entre l'apparence claire et sombre.",
    accountStatus: "Statut du Compte",
    emailVerified: "Email vérifié",
    emailPending: "Email en attente de vérification",
    planLimits: "Limites du Plan",
    usageSync: "Utilisation synchronisée avec votre compte.",
    history: "Historique",
    days: "jours",
    notes: "Notes",
    entities: "Entités",
    activities: "Activités",
    vault: "Coffre-fort",
    unlimited: "Illimité",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const saved = localStorage.getItem("language") as Language;
    return saved && ["en", "es", "pt", "fr"].includes(saved) ? saved : "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};