import type { ComponentType, SVGProps } from "react";
import {
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  SparklesIcon,
  FireIcon,
  ClockIcon,
  UserGroupIcon,
  ArrowTrendingUpIcon,
  DocumentTextIcon,
  ShareIcon,
  MagnifyingGlassIcon,
  XMarkIcon,
  CheckIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  Bars3Icon,
  ViewfinderCircleIcon,
  PlusIcon,
  FolderOpenIcon,
  TrashIcon,
  ArrowTopRightOnSquareIcon,
  ArrowRightOnRectangleIcon,
  LinkIcon,
  TagIcon,
  PlayIcon,
  PauseIcon,
  PhotoIcon,
  HashtagIcon,
  AtSymbolIcon,
  UserIcon,
  UserCircleIcon,
  FolderIcon,
  BuildingOffice2Icon,
  ChartBarIcon,
  GlobeAltIcon,
  CodeBracketIcon,
  CodeBracketSquareIcon,
  PencilSquareIcon,
  BoltIcon,
  Squares2X2Icon,
  ViewColumnsIcon,
  ChartBarSquareIcon as GaugeIcon,
  CheckBadgeIcon,
  TrophyIcon,
  RocketLaunchIcon,
  EnvelopeIcon,
  MoonIcon,
  SunIcon,
  CalendarDaysIcon,
  LockClosedIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  ChatBubbleLeftEllipsisIcon,
  ListBulletIcon,
  BoldIcon,
  ItalicIcon,
  StrikethroughIcon,
  MusicalNoteIcon,
  RectangleStackIcon,
  BookmarkIcon,
  BookmarkSquareIcon,
  AdjustmentsHorizontalIcon,
  ServerStackIcon,
  CpuChipIcon,
  DocumentIcon,
  MinusIcon,
  TableCellsIcon,
  ArrowsUpDownIcon,
  Cog6ToothIcon,
  MagnifyingGlassPlusIcon,
  MagnifyingGlassMinusIcon,
  EyeIcon,
  EyeSlashIcon,
} from "@heroicons/react/24/outline";

export type LucideIcon = ComponentType<SVGProps<SVGSVGElement>>;

export {
  ArrowRightIcon as ArrowRight,
  ArrowLeftIcon as ArrowLeft,
  ArrowPathIcon as Loader2,
  SparklesIcon as Sparkles,
  FireIcon as Flame,
  ClockIcon as Clock,
  ClockIcon as Timer,
  UserGroupIcon as Users,
  ArrowTrendingUpIcon as TrendingUp,
  DocumentTextIcon as StickyNote,
  DocumentTextIcon as FileText,
  ShareIcon as Network,
  MagnifyingGlassIcon as Search,
  XMarkIcon as X,
  CheckIcon as Check,
  ChevronRightIcon as ChevronRight,
  ChevronLeftIcon as ChevronLeft,
  ChevronDownIcon as ChevronDown,
  ChevronUpIcon as ChevronUp,
  EllipsisHorizontalIcon as MoreHorizontal,
  Bars3Icon as Menu,
  ViewfinderCircleIcon as Circle,
  ViewfinderCircleIcon as Dot,
  ViewfinderCircleIcon as CircleDot,
  PlusIcon as Plus,
  FolderOpenIcon as FolderOpen,
  TrashIcon as Trash2,
  ArrowTopRightOnSquareIcon as ArrowUpRight,
  LinkIcon as Link,
  LinkIcon as Link2,
  TagIcon as Tag,
  PlayIcon as Play,
  PauseIcon as Pause,
  PhotoIcon as ImageOff,
  HashtagIcon as Hash,
  HashtagIcon as Heading1,
  HashtagIcon as Heading2,
  HashtagIcon as Heading3,
  AtSymbolIcon as AtSign,
  UserIcon as User,
  FolderIcon as Folder,
  BuildingOffice2Icon as Building2,
  ChartBarIcon as BarChart3,
  ChartBarIcon as GitGraph,
  Squares2X2Icon as Layers,
  Squares2X2Icon as Squares2x2,
  ViewColumnsIcon as LayoutDashboard,
  PencilSquareIcon as Edit,
  PencilSquareIcon as PenLine,
  BoltIcon as Zap,
  GlobeAltIcon as GlobeAlt,
  GaugeIcon as Gauge,
  CheckBadgeIcon as BadgeCheck,
  TrophyIcon as Crown,
  RocketLaunchIcon as Rocket,
  EnvelopeIcon as Mail,
  MoonIcon as Moon,
  SunIcon as Sun,
  CalendarDaysIcon as Calendar,
  LockClosedIcon as Lock,
  ArrowDownTrayIcon as Download,
  ArrowUpTrayIcon as Upload,
  ChatBubbleLeftEllipsisIcon as Quote,
  ListBulletIcon as List,
  ListBulletIcon as ListOrdered,
  CheckBadgeIcon as ListTodo,
  CodeBracketIcon as Code,
  CodeBracketSquareIcon as Code2,
  BoldIcon as Bold,
  ItalicIcon as Italic,
  StrikethroughIcon as Strikethrough,
  MusicalNoteIcon as Music,
  RectangleStackIcon as PanelLeft,
  Bars3Icon as GripVertical,
  SparklesIcon as Gem,
  ArrowPathIcon as RefreshCw,
  ArrowTopRightOnSquareIcon as ExternalLink,
  BookmarkIcon as Bookmark,
  BookmarkSquareIcon as BookmarkCheck,
  PhotoIcon as Image,
  PhotoIcon as ImageIcon,
  AdjustmentsHorizontalIcon as SlidersHorizontal,
  ServerStackIcon as HardDrive,
  CpuChipIcon as Activity,
  ArrowRightOnRectangleIcon as LogOut,
  ArrowRightOnRectangleIcon as PanelRight,
  UserCircleIcon as UserCircle,
  ArrowsUpDownIcon as ChevronsUpDown,
  MinusIcon as Minus,
  TableCellsIcon as Table,
  DocumentIcon as File,
  DocumentTextIcon as Type,
  SparklesIcon as Brain,
  Cog6ToothIcon as Settings,
  Cog6ToothIcon as Settings2,
  ArrowDownTrayIcon as Save,
  EllipsisVerticalIcon as MoreVertical,
  MagnifyingGlassPlusIcon as ZoomIn,
  MagnifyingGlassMinusIcon as ZoomOut,
  EyeIcon as Eye,
  EyeSlashIcon as EyeOff,
  ShareIcon as Share2,
};
